feat: add oocana-python test case

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -49,20 +49,97 @@ jobs:
       - name: Test
         timeout-minutes: 10
         run: cargo test --workspace --exclude layer
+      - name: build oocana
+        run: cargo build
+      - name: upload oocana
+        uses: actions/upload-artifact@v4
+        with:
+          name: oocana
+          path: target/debug/oocana
+  test-node:
+    runs-on: ubuntu-latest
+    needs: [skip, build]
+    steps:
+      - name: Download oocana
+        uses: actions/download-artifact@v4
+        with:
+          name: oocana
+          path: target/debug/oocana
       - uses: oomol/oocana-node/.github/actions/oocana-node@main
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           path: oocana-node
-      - name: replace oocana # cargo test will build the binary, so we only need to copy it
+      - name: Start MQTT Broker
+        run: |
+          sudo apt update && sudo apt install -y --no-install-recommends mosquitto
+          mosquitto -d -p 47688
+      - name: replace oocana# cargo test will build the binary, so we only need to copy it
         run: cp target/debug/oocana oocana-node/packages/oocana/
       - name: test flow and other oocana api
         run: pnpm run test
         working-directory: oocana-node
-      - name: upload logs # only enable when debugging
+      - name: upload node logs
         uses: actions/upload-artifact@v4
         with:
-          name: oocana-logs
+          name: oocana-node-logs
           path: |
             ~/.oocana/sessions/
           retention-days: 1
         if: failure()
+  test-python:
+    runs-on: ubuntu-latest
+    needs: [skip, build]
+    steps:
+      - uses: oomol/oocana-python/.github/actions/oocana-python@main
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          path: oocana-python
+      - name: Start MQTT Broker
+        run: |
+          sudo apt update && sudo apt install -y --no-install-recommends mosquitto
+          mosquitto -d -p 47688
+      - name: Download oocana
+        uses: actions/download-artifact@v4
+        with:
+          name: oocana
+          path: target/debug/oocana
+      - name: install oocana-python
+        run: |
+          cd flow-examples
+          npm install
+        working-directory: oocana-python
+      - name: replace oocana
+        run: |
+          cp target/debug/oocana flow-examples/node_modules/@oomol/oocana/
+        working-directory: oocana-python
+      - name: test flow and other oocana api
+        run: |
+          source .venv/bin/activate
+          cd flow-examples
+          npm run test
+        working-directory: oocana-python
+      - name: upload logs # only enable when debugging
+        uses: actions/upload-artifact@v4
+        with:
+          name: oocana-python-logs
+          path: |
+            ~/.oocana/sessions/
+          retention-days: 1
+        if: failure()
+  check:
+    runs-on: ubuntu-latest
+    needs: [skip, test-python, test-node]
+    if: ${{ always() }}
+    steps:
+      - name: check
+        run: |
+          exit_on_result() {
+            if [[ "$2" == "failure" || "$2" == "cancelled" ]]; then
+              echo "Job '$1' failed or was cancelled."
+              exit 1
+            fi
+          }
+
+          exit_on_result "test-node" "${{ needs.test-node.result }}"
+          exit_on_result "test-python" "${{ needs.test-python.result }}"
+          echo all needs jobs : "${{ toJson(needs)}}"
